# Generated by Django 3.2.6 on 2022-01-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIObjectAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("currency", "Currency"),
                        ],
                        default="string",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Object Attribute",
                "db_table": "docs_object_attribute",
            },
        ),
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "docs_app",
            },
        ),
        migrations.CreateModel(
            name="APIObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("data", models.TextField()),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="docs.app"
                    ),
                ),
            ],
            options={
                "db_table": "docs_object",
            },
        ),
        migrations.CreateModel(
            name="API",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "path",
                    models.CharField(
                        blank=True, default=None, max_length=1024, null=True
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        default="https://api.finmachines.com/v1/",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=8,
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("inputs", models.TextField(blank=True, default=None, null=True)),
                ("output", models.TextField(blank=True, default=None, null=True)),
                ("curl", models.TextField(blank=True, default=None, null=True)),
                ("python", models.TextField(blank=True, default=None, null=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="docs.app"
                    ),
                ),
            ],
            options={
                "verbose_name": "REST API",
                "verbose_name_plural": "REST API",
                "db_table": "docs_api",
                "ordering": ["id", "url", "action"],
                "unique_together": {("app", "action", "url")},
            },
        ),
    ]
